version: '3.3'
services:
  consul:
    image: consul:1.4.2
    command: agent -dev -ui -client 0.0.0.0
    ports:
      - "8500:8500"
  service:
    image: poc/ipblock-pool
    ports:
      - "5555:5555"
    environment:
      - CONSUL_ADDR=consul:8500
    depends_on:
      - consul
